### ISSUE TITLE
Getting MNIST data in the required format

### ISSUE THREAD

**Issue by ineaugh** [anokland/dfa-torch#1]
How do I get the MNIST data in the format that can be used by the code, i.e. the mnist-train.t7 and mnist-test.t7 files? The script from https://github.com/soumith/cifar.torch.git only retrieves CIFAR data.

**Comment by anokland** [comment]
Hi,
I don't remember actually. I will check it out tomorrow and let you know.

Arild
1. sep. 2016 14.43 skrev "ineaugh" notifications@github.com:

**Comment by anokland** [comment]
I have modified Data.lua to get the MNIST dataset using the MNIST module (https://github.com/andresy/mnist). You have to install this and it should work, see updated readme.
