### ISSUE TITLE
DFA relu low accuracy problem

### ISSUE THREAD

**Issue by hdh4797** [anokland/dfa-torch#2]
Thank you for providing good simulation code.

But When I run DFA with relu activation function it has very low accuracy.

Is it the problem of code? or the limits of algorithm DFA?

**Comment by anokland** [comment]
Hi,

For deeper networks than 2-3 layers, ReLU performs worse than Tanh
networks. This is due to DFA, I do not think it is a bug.

If it is much worse, you could try to lower your learning rate.

Arild

2017-06-21 4:32 GMT+02:00 hdh4797 <notifications@github.com>:
