### ISSUE TITLE
FA simulation error

### ISSUE THREAD

**Issue by hdh4797** [anokland/dfa-torch#3]
To simulate FA, I wrote following command,
"th Main.lua -dataset Cifar10 -network conv.lua -LR 9e-6 -whiten -gradient fa -epoch 101"

But It stopped working because of the error. (THNN.lua:110: bad argument #8 tp 'v')

Do you know why does it not work?

![fa_error](https://user-images.githubusercontent.com/16893084/27380728-4869d05a-56bb-11e7-9f97-b5a2885dd12b.JPG)

**Comment by anokland** [comment]
This is because of changes in nn implementation of SpatialConvolution.lua. I have updated the file Models/SpatialConvolution.lua to fix the issue.
