### ISSUE TITLE
-whiten arg not working anymore

### ISSUE THREAD

**Issue by iacolippo** [anokland/dfa-torch#4]
Hi, I think some updates in the `unsup` package broke the whitening procedure in your code. The problem should be the `zca_whiten` function. 

The code gets stuck for an indefinite amount of time there. Then, at some point:

```
/home/iacolippo/torch/install/bin/luajit: /home/iacolippo/torch/install/share/lua/5.1/trepl/init.lua:389: 
Lapack Error syev : 3070 off-diagonal elements didn't converge to zero at 
/home/iacolippo/torch/pkg/torch/lib/TH/generic/THTensorLapack.c:384
stack traceback:
	[C]: in function 'error'
	/home/iacolippo/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	Main.lua:83: in main chunk
	[C]: in function 'dofile'
	...ippo/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

Tried with `th Main.lua -dataset Cifar10 -network conv.lua -LR 5e-5 -whiten`

**Comment by anokland** [comment]
I tried the command you are running, and it works for me. I also tried to update the "unsup" package and it still works. I think the problem you are seeing has another cause.

**Comment by iacolippo** [comment]
Stupid question: do you already have a PreProcData folder?

Can you tell me which version of Torch are you using?

Last log on my `torch` folder history:

> commit 5c1d3cfda8101123628a45e70435d545ae1bc771
> Merge: 54a378a 296022d
> Author: Soumith Chintala <soumith@gmail.com>
> Date:   Wed Jun 7 18:16:42 2017 -0400

**Comment by anokland** [comment]
Yes, I already had a PreProcFolder. When I delete it, the startup takes some minutes to complete, but eventually continues as normal.

My torch version is one commit newer than yours:

commit 5961f52a65fe33efa675f71e5c19ad8de56e8dad
Author: soumith <soumith@fb.com>
Date:   Fri Jun 23 12:34:03 2017 -0700
